// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-3ZFkHLVKtaLNwbMvRtBzpp4vNHpX1w',
    appId: '1:455956723734:web:3c745c59f959a1df9f5d37',
    messagingSenderId: '455956723734',
    projectId: 'umamusume-trainer-app',
    authDomain: 'umamusume-trainer-app.firebaseapp.com',
    storageBucket: 'umamusume-trainer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgxCFhFboVjbBtDjhCUGte1s20gmdqdVY',
    appId: '1:455956723734:android:b706ca54ab5d90279f5d37',
    messagingSenderId: '455956723734',
    projectId: 'umamusume-trainer-app',
    storageBucket: 'umamusume-trainer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMaAlHy2l9G6Bp_KHI9UcCVCHzkzgpczc',
    appId: '1:455956723734:ios:50672cbb8c937e7a9f5d37',
    messagingSenderId: '455956723734',
    projectId: 'umamusume-trainer-app',
    storageBucket: 'umamusume-trainer-app.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMaAlHy2l9G6Bp_KHI9UcCVCHzkzgpczc',
    appId: '1:455956723734:ios:50672cbb8c937e7a9f5d37',
    messagingSenderId: '455956723734',
    projectId: 'umamusume-trainer-app',
    storageBucket: 'umamusume-trainer-app.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm-3ZFkHLVKtaLNwbMvRtBzpp4vNHpX1w',
    appId: '1:455956723734:web:05871a48a10b79f89f5d37',
    messagingSenderId: '455956723734',
    projectId: 'umamusume-trainer-app',
    authDomain: 'umamusume-trainer-app.firebaseapp.com',
    storageBucket: 'umamusume-trainer-app.firebasestorage.app',
  );
}
